### ISSUE TITLE
kaigara render send diagnostics to stderr, not to stdout

### ISSUE THREAD

**Issue by askoriy** [mod/kaigara#16]
kaigara render gerrit.config > /opt/gerrit/site/etc/gerrit.config

cat /opt/gerrit/site/etc/gerrit.config
**No configuration found**
Using metafile: /opt/provision/metadata.yml
[gerrit]
    basePath = git

**Comment by dkkoval** [comment]
I'll send a patch to fix it in ~1 hour

**Comment by mod** [comment]
Resolved

**Comment by mod** [comment]
Resolved by #17
